development:
  adapter: postgresql
  encoding: unicode
  database: pegasus_development
  template: template0
  pool: 5
  username: ubuntu
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: pegasus_test
  template: template0
  pool: 5
  username: ubuntu
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: pegasus_production
  template: template0
  pool: 5
  username: ubuntu
  password: