development:
  adapter: postgresql
  encoding: unicode
  database: pegasus_development
  template: template0
  pool: 5
  username: ubuntu
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: pegasus_test
  template: template0
  pool: 5
  username: ubuntu
  password:
  
production:
  adapter: postgresql  
  host: ec2-23-21-96-129.compute-1.amazonaws.com      # HOST 
  port: 5432                                          # Port  
  database: dcbbsd77h1br53                            # Database Name  
  username: rcpkpngixvoqeo                            # User Name  
  password: '< password >'                            # Password 