development:
  adapter: postgresql
  encoding: UTF8
  database: pegasus_development
  template: template0
  pool: 5
  timeout: 5000
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: UTF8
  database: pegasus_test
  template: template0
  pool: 5
  timeout: 5000
  username: ubuntu 
  password:

production:
  adapter: postgresql
  encoding: UTF8
  database: dcbbsd77h1br53
  template: template0
  pool: 5
  timeout: 5000
  username: rcpkpngixvoqeo
  password: